theme: jekyll-theme-cayman
title: Jupiter Project - UofAlberta Libraries
description: Jupiter is a University of Alberta Libraries-based initiative to create a sustainable and extensible digital asset management system. This is phase 1 (IR).
